name: 'CI/CD Deployment for Java Web App'
description: 'Composite Action for building and deploying the Java web application using Docker and Helm on AWS.'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  docker-username:
    description: 'DockerHub username'
    required: true
  docker-password:
    description: 'DockerHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout "webapp" branch
      uses: actions/checkout@v3
      with:
        ref: webapp

    - name: Set up Maven 3.9
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven

    - name: Build with Maven
      working-directory: ./webapp
      run: mvn clean package --file webapp_project/pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push Docker image to DockerHub
      working-directory: ./webapp
      run: |
        docker build -t qwerty99/webapp:java-17-ci-cd-01 -f Dockerfile .
        docker push qwerty99/webapp:java-17-ci-cd-01

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Update Kubeconfig for EKS Cluster
      run: |
        aws sts get-caller-identity
        # aws eks --region ${{ inputs.aws-region }} update-kubeconfig --name webapp-eks

    - name: Deploy helm chart on eks
      working-directory: ./webapp_helm
      run: |
        ls -altr
        helm version
        # helm install webapp webapp --namespace webapp --create-namespace
