name: 'AWS EKS Infrastructure Provisioning'
description: 'Composite Action for provisioning AWS infrastructure using Terraform.'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: webapp

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      working-directory: ./eks_infra/eks_cluster
      run: terraform init

    - name: Plan AWS Infrastructure
      working-directory: ./eks_infra/eks_cluster
      run: terraform plan -out=plan.tfplan

    # Uncomment this step to apply the infrastructure
    # - name: Apply AWS EKS Infrastructure
    #   working-directory: ./eks_infra/eks_cluster
    #   run: terraform apply -auto-approve plan.tfplan

