name: CI/CD Pipeline for Java Web App

on:
  push:
    branches:
      - webapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run CI/CD Deployment Action
        uses: ./github/actions/cicd-action  # Reference the composite action
        with:
          aws-region: 'us-east-1'
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # Pass the IAM Role ARN from GitHub secrets
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
