name: Deploy Infrastructure to AWS EKS

on:
  push:
    branches:
      - webapp 

jobs:
  terraform-setup:
    name: Set up Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: webapp

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        
  eks-infrastructure:
    name: Provision AWS EKS
    runs-on: ubuntu-latest
    needs: terraform-setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: webapp

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Initialize Terraform
        working-directory: ./terraform/aws-infrastructure
        run: terraform init

      - name: Validate Terraform
        working-directory: ./eks_infra/eks_cluster
        run: terraform validate

      - name: Plan AWS Infrastructure
        working-directory: ./eks_infra/eks_cluster
        run: terraform plan -out=plan.tfplan

      # - name: Apply AWS EKS Infrastructure
      #   working-directory: ./eks_infra/eks_cluster
      #   run: terraform apply -auto-approve plan.tfplan

  eks-ingress:
    name: Provision AWS EKS Cluster
    runs-on: ubuntu-latest
    needs: eks-infrastructure
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: webapp

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Initialize Terraform for EKS Cluster
        working-directory: ./eks_infra/ingress
        run: terraform init

      - name: Validate Terraform for EKS Cluster
        working-directory: ./eks_infra/ingress
        run: terraform validate

      - name: Plan EKS Cluster
        working-directory: ./eks_infra/ingress
        run: terraform plan -out=eks-plan.tfplan

      # - name: Apply EKS Cluster
      #   working-directory: ./eks_infra/ingress
      #   run: terraform apply -auto-approve eks-plan.tfplan
