name: "Provision AWS EKS Infrastructure with Assume Role"

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  eks-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Use Terraform with Assume Role
        uses: ./.github/actions/infra-action
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # The ARN of the role to assume
          aws-region: 'us-east-1'
          working-directory: './eks_infra/eks_cluster'
          auto-apply: 'true'  # Automatically apply the plan after Terraform plan
		  
  eks-ingress:
    name: Install AWS EKS ALB ingress
    runs-on: ubuntu-latest
    needs: eks-infrastructure
    steps:
      - name: Use Terraform with Assume Role
        uses: ./.github/actions/infra-action
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # The ARN of the role to assume
          aws-region: 'us-east-1'
          working-directory: './eks_infra/ingress'
          auto-apply: 'true'  # Automatically apply the plan after Terraform plan
    
